# Generated by Django 2.1.4 on 2019-01-05 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('plot', models.TextField()),
                ('year', models.PositiveIntegerField()),
                ('rating', models.PositiveIntegerField(choices=[(0, 'not-rated'), (1, 'suitable for children'), (2, 'suitable with parental guide'), (3, 'Adult only')])),
                ('website', models.URLField(blank=True)),
                ('runtime', models.PositiveIntegerField()),
            ],
        ),
    ]
