# Generated by Django 2.1.4 on 2019-01-05 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='rating',
            field=models.PositiveIntegerField(choices=[(0, 'not-rated'), (1, 'suitable for children'), (2, 'suitable with parental guide'), (3, 'Adult only')], default=0),
        ),
    ]
